# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash:5.6.2

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json

# install generator plugin
# RUN /usr/share/logstash/bin/logstash-plugin install logstash-input-generator